Develop
vladsav33/java-filmorate pull request #13
Opened 2023-05-05 21:30 UTC by vladsav33

Merged develop branch into main branch by mistake. We created a new pull request

2023-05-06 09:35 UTC, vladsav33 commented
Ссылка на первоначальный pull request
https://github.com/vladsav33/java-filmorate/pull/6

2023-05-06 21:57 UTC, AnastasiyaFomkina requested changes
Осталось совсем чуть-чуть

2023-05-06 21:57 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
Нужно удалить кавычки из названия

2023-05-06 21:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-05-06 21:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getById(id).get();
Прежде чем получать значение из `Optional` нужно убедиться, что он не пустой. Можно воспользоваться любым способом из [данной статьи](https://habr.com/ru/post/346782/#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%2C%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%89%D0%B8%D0%B9%D1%81%D1%8F%20%D0%B2%20Optional%3F)
Нужно поправить во всех местах

2023-05-06 21:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +    public void validateDirector(Director director) {
Нигде не используется

2023-05-07 08:29 UTC, Kuros85Ya commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
Это невозможно. В h2 USER - зарезервированное слово, и не может использоваться как название таблицы. Кавычки введены для обхода этого ограничения

2023-05-07 08:31 UTC, Kuros85Ya commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Мы прочитали статью и обсудили этот момент между собой и в том числе в группе. Да, в каких-то ситуациях - например, при использовании Hibernate и Spring JPA - использовать `@Data` может быть вредно, и этого нужно избегать.

Но в данном случае аннотация работает ровно так, как мы хотим, чтобы она работала: переопределяла .toString(), .hashCode(), .equlas() и геттеры и сеттеры. На нашем сете технологий вреда от этой аннотации нет.

Мы не используем бездумно, мы используем сознательно.

2023-05-07 08:48 UTC, vladsav33 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getById(id).get();
На уровне DAO только методы getById(int id) и update(Director director) возвращают объект типа Optional. Чтобы убедиться, что возвращаемый объект типа Optional не пустой, в сервисном слое DirectorService в методах getById(int id) и update(Director director) осуществляется проверка посредством checkIfDirectorExists(int id) - здесь как раз применяется метод .orElseThrow() из вышеуказанной статьи.

2023-05-07 09:00 UTC, Kuros85Ya commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
В теории Практикума рекомендовали всегда переопределять методы .equals(), hashCode(), .toString()
В ТЗ9 также давалась подсказка по использованию этой аннотации.

О проблемах в будущем, при использовании Hinernate, мы осведомлены
 Но здесь с её применением всё ок
![236468393-192f569b-f59d-45b1-80d4-871802bd2ea7](https://user-images.githubusercontent.com/109678766/236668120-274d3e63-3acd-4032-ac5c-177e70bea00a.jpg)

2023-05-07 09:08 UTC, vladsav33 commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +    public void validateDirector(Director director) {
Исправлено

2023-05-07 12:22 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
Так можно же вернуть начальное название. Заключать название таблицы в кавычки считается плохим тоном. Нужно переименовать название таблицы, чтобы оно соответствовало code-style

2023-05-07 12:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Продублировала данное сообщение, так как обновился pr, чтобы не потерялось. Данный момент подсветила в качестве дополнительной информации, так как аннотация `@Data` является не очень однозначной и может провоцировать неявные проблемы. Переписывать все не обязательно, но изучить статью советую

2023-05-07 12:38 UTC, AnastasiyaFomkina requested changes

2023-05-07 12:38 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getById(id).get();
Прошу прощения, не обратила внимание на метод `checkIfDirectorExists`

2023-05-07 12:38 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void checkIfDirectorExists(int id) {
Должен возвращать `Director`, а не `void`. Нет смысла два раза доставать один и тот же объект только ради проверки, если можно объединить проверку и получение

2023-05-07 12:38 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        directorStorage.getById(id)
Соответственно тут нужно просто добавить `return`:
```suggestion
        return directorStorage.getById(id)
```
Так как `orElseThrow` разворачивает `Optional`, если он не пуст, или выбрасывает исключение, когда `Optional` пустой

Соответственно метод `checkIfDirectorExists` нужно будет переименовать в `getIfDirectorExists`, и сразу возвращать результат работы данного метода в `getById` и `update`

2023-05-07 14:21 UTC, Kuros85Ya commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
Начальное название не подходит, так как теория требует единства стиля в названии таблиц. Если `director`, `genre`, то должен быть `user`, а не `users`.
Как вариант можем сделать `filmorate_user`

2023-05-07 14:30 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void checkIfDirectorExists(int id) {
Исправлено.

2023-05-07 14:34 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        directorStorage.getById(id)
Исправлено: метод `checkIfDirectorExists` переименован в `getIfDirectorExists`, метод `getById` в `DirectorService` оптимизирован. 
По поводу метода `update`: возвращать результат работы метода `getIfDirectorExists` там нельзя. Логика метода `update` такова:
1. С помощью метода `getIfDirectorExists` проверяется, существует ли в БД режиссер, параметры которого нужно изменить (при этом результатом работы метода `getIfDirectorExists` будет текущий, еще не измененный в БД режиссер).
2. Если режиссер существует, то на уровне DAO вносятся изменения найденному режиссеру (в противном случае, выбрасывается ошибка).
3. После внесения изменений метод `update` возвращает измененного режиссера.

2023-05-07 16:57 UTC, vladsav33 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Статью изучили

2023-05-07 21:19 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
`filmorate_user` подойдет лучше

2023-05-07 21:30 UTC, AnastasiyaFomkina approved these changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Молодцы, что выбрали не самые легкие задания. Вы хорошо разобрались во взаимодействие между слоями сервис - контроллер - репозиторий.  У вас получились отличные запросы к таблицам. И клево, что вы изучаете дополнительную информацию и не стесняетесь аргументировать свою позицию :)

2023-05-07 22:02 UTC, Kuros85Ya commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "user" (
Сделали

2023-05-08 15:22 UTC, merged