Sprint #9
vladsav33/java-filmorate pull request #2
Opened 2023-03-05 15:56 UTC by vladsav33

Added RestControllers for users and films

2023-03-06 13:14 UTC, AnastasiyaFomkina requested changes

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration) {
Можно заменить на аннотацию [@AllArgsConstructor](https://habr.com/ru/company/piter/blog/676394/#:~:text=%40NoArgsConstructor%2C%C2%A0%40RequiredArgsConstructor%2C-,%40AllArgsConstructor,-%D0%9A%D0%BE%D0%B3%D0%B4%D0%B0%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%20%D0%B0%D0%BD%D0%BD%D0%BE%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD) от lombok

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (email == null || email.isEmpty() || !email.contains("@") ||
Можно дописать данную проверку с помощью [аннотаций валидации](https://www.baeldung.com/javax-validation). `@Email` уже содержит проверку на наличие "@"

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +                birthday.isAfter(LocalDate.now())) {
[@PastOrPresent](https://www.baeldung.com/javax-validation#:~:text=%40Past%20and-,%40PastOrPresent,-validate%20that%20a)

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +                releaseDate.isBefore(LocalDate.of(1895, Month.DECEMBER, 28)) ||
Можно написать свою [кастомную аннотацию валидации](https://reflectoring.io/bean-validation-with-spring-boot/#a-custom-validator-with-spring-boot:~:text=to%20none.-,A%20Custom%20Validator%20with%20Spring%20Boot,-If%20the%20available)

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (name == null ||  name.isEmpty() || description.length() > 200 ||
Можно добавить [@Size](https://www.baeldung.com/javax-validation#:~:text=value%20is%20true.-,%40Size,-validates%20that%20the) для проверки длины. А проверку на null и empty заменить аннотацией [@NotEmpty](https://www.baeldung.com/javax-validation#:~:text=in%20the%20JSR%3A-,%40NotEmpty,-validates%20that%20the)

2023-03-06 13:14 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +                Duration.ofMinutes(duration).isNegative() || Duration.ofMinutes(duration).isZero()) {
[@PositiveOrZero](https://www.baeldung.com/javax-validation#:~:text=%40Positive%20and-,%40PositiveOrZero,-apply%20to%20numeric)

2023-03-08 14:57 UTC, vladsav33 commented
Added validation through annotations

2023-03-09 08:17 UTC, AnastasiyaFomkina requested changes
Молодец, что разобрался со спринговой валидацией 👍

2023-03-09 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDateValidator.java
> +        if (value.isBefore(LocalDate.of(1895, Month.DECEMBER, 28))) {
Можно сократить проверку до одной строчки:
```suggestion
        return !value.isBefore(LocalDate.of(1895, Month.DECEMBER, 28));
```

2023-03-09 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        List<Film> result = new ArrayList<>(films.values());
Так как переменная больше нигде не используется, лучше сразу возвращать список:
```suggestion
        return new ArrayList<>(films.values());
```

2023-03-09 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDate.java
> +public @interface ReleaseDate {
🔥

2023-03-09 09:54 UTC, vladsav33 commented
Removed redundant variables

2023-03-09 11:16 UTC, AnastasiyaFomkina approved these changes

2023-03-09 14:49 UTC, merged