feat: Added friends and likes
vladsav33/java-filmorate pull request #4
Opened 2023-03-16 12:27 UTC by vladsav33

2023-03-16 17:05 UTC, AnastasiyaFomkina requested changes

2023-03-16 17:05 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public Map<Integer, User> getUsers() {
Не используется, нужно удалить

2023-03-16 17:05 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        for (int id : users.get(userId).getFriends()) {
Все циклы нужно переписать с помощью [stream api](https://habr.com/ru/company/otus/blog/658999/)

2023-03-16 17:05 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/UserTest.java
> +    public UserStorage userStorage;
Лучше заменить модификатор доступа на `private`, так как используем только в данном тесте

2023-03-16 17:05 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +    public UserStorage userStorage;
Лучше стараться максимально ограждать объекты от непреднамеренных изменений. Если мы не используем тот или иной объект за пределами класса, нужно ставить максимально строгий модификатор доступа `private`, чтобы не было возможности как-либо изменить объект из другой части программы

2023-03-17 08:09 UTC, vladsav33 commented
Refactored - moved Storage dependency to the Service level

2023-03-17 13:19 UTC, AnastasiyaFomkina requested changes

2023-03-17 13:19 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            count = 10;
Лучше воспользоваться параметром [defaultValue](https://www.baeldung.com/spring-request-param#a-default-value-for-the-request-parameter:~:text=A%20Default%20Value%20for%20the%20Request%20Parameter) аннотации `@RequestParam`, тогда код станет чуть короче и не придется писать проверку на `null`

2023-03-17 13:19 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +        log.warn("User was not found");
Лучше логировать `message` исключения

2023-03-17 14:15 UTC, vladsav33 commented
Added default value to the count parameter
Added message to error logging

2023-03-18 07:39 UTC, AnastasiyaFomkina approved these changes

2023-03-18 07:57 UTC, merged